### ISSUE TITLE
g++ and gcc to version 9.3.0

### ISSUE THREAD

**Issue by mkolodziejczyk-piap** [uzh-rpg/agile_flight#10]
Hi,
Is this requirement strict or just g++/gcc >= 9.3 is enough? Because the default version in Ubuntu 20 is 9.4.0. The downgrade from 9.4 to 9.3 is not so easy and it's not described in the referenced link. I've managed to build and run the stack so far with 9.4 but wonder if I should go further with this setup. Regards,

**Comment by yun-long** [comment]
no, it is not strictly required to use gcc/g++ 9.3
9.4 is perfectly fine
