### ISSUE TITLE
training on cloud 

### ISSUE THREAD

**Issue by LianhaoYin** [uzh-rpg/agile_flight#11]
I met a few problems to compile on the cloud, such as GCC version issues. 

Could you help to indicate which files shall be move to cloud without compile on the cloud. 

Could you help to provide a simplified [setup_py.bash](https://github.com/uzh-rpg/agile_flight/blob/main/setup_py.bash) which can be used on cloud with compiled files transferred from local machine to cloud.

**Comment by yun-long** [comment]
hi

it is necessary to compile the source code. there is no simple way of just "move files to cloud".

I would recommend using Docker if you want to train on the cloud.
We are planning to provide a Docker file, but this is not guaranteed since we are currently very busy with other research projects
