### ISSUE TITLE
Could we change environment during training?

### ISSUE THREAD

**Issue by ouafi98** [uzh-rpg/agile_flight#12]
Hi, I want to switch to other environment automatically during training. Is that possible with the actual provided code ?

Also can we use both depth image and distance from obstacles?

Does the simulator give only the distance of obstacles in front of the drone ?

**Comment by yun-long** [comment]
yes. you can change environment during training. however, this is not implemented. It is possible with the actually provided code. 

Yes. you can use both during training. But for evaluation, you can only use one of them

The simulator provides 10 closed distances between the drone and the obstacles. Not only the obstacles that are in front.
