### ISSUE TITLE
Unable to run the vision-flight demo

### ISSUE THREAD

**Issue by insaaniManav** [uzh-rpg/agile_flight#19]
I ran through the install script, first setup_ros.bash then setup_py.bash everything ran without an error but when I run the vision demo I get the below 

```
Traceback (most recent call last):
  File "run_vision_demo.py", line 10, in <module>
    from rpg_baselines.torch.envs import vec_env_wrapper as wrapper
ModuleNotFoundError: No module named 'rpg_baselines.torch'
```

**Comment by ouafi98** [comment]
see here : https://github.com/uzh-rpg/agile_flight/issues/5
