### ISSUE TITLE
obstacle avoidance?

### ISSUE THREAD

**Issue by ngthanhtin** [uzh-rpg/agile_flight#21]
Hi i would like to ask how to adjust the env for  terminating when encounter an obstacle.
In vision_env.cpp, I have changed the code as following:
![Screenshot from 2022-04-01 15-31-49](https://user-images.githubusercontent.com/17596799/161207975-2da885d2-1af5-4eed-99e8-ea6123c7c0b9.png)
and then,
`catkin build flightlib`
But the agent still is going through obstacles as the following video:
https://www.youtube.com/watch?v=350ardLDI1Q&ab_channel=T%C3%ADnNguy%E1%BB%85n

So could you tell me how to do this?

Thanks

**Comment by yun-long** [comment]
this code is used for reinforcement learning, which does not use any ROS. 

when you change the vision_env.cpp, you should do

```
cd flightlib/build
cmake ..
make -j10
pip install . 
```

by doing so, the flightgym python package will be updated. 
the flightgym package is used in the (run_vision_ppo.py)[https://github.com/uzh-rpg/agile_flight/blob/main/envtest/python/run_vision_ppo.py]

**Comment by ngthanhtin** [comment]
Thanks, I did it.
