### ISSUE TITLE
Custom reward function

### ISSUE THREAD

**Issue by yukaryote** [uzh-rpg/agile_flight#22]
For the DodgeDrone competition, what is the best way to go about making our custom reward function? Currently, the reward function seems to be defined in the Flightmare flightrl source code, which we would have to recompile every time we edit the reward function.

**Comment by yun-long** [comment]
the best way is indeed to change the source code in flightmare,
it is actually not that complicated.  every time after changing the code , you only need to recompile the code by

```
cd flightlib/build
cmake ..
make -j10
pip install . 
```

**Comment by yukaryote** [comment]
Thanks!
