### ISSUE TITLE
Obstacle in state-based case

### ISSUE THREAD

**Issue by soldierofhell** [uzh-rpg/agile_flight#3]
Hi, I've got question about obstacle definition in state-based case. README states about "metric distance to obstacles". On the other hand Obstacle msg has position and scale. Is position relative? What exactly is scale? Regards,

**Comment by yun-long** [comment]
The relative position between the center of the quadrotor and the center of the sphere obstacles. 
The scale means the size of the obstacles, in radius.

it is defined in
[here](https://github.com/uzh-rpg/flightmare/blob/dev/version_22/flightlib/src/envs/vision_env/vision_env.cpp#L142-L235)

**Comment by soldierofhell** [comment]
Great, thanks
