### ISSUE TITLE
Goals?

### ISSUE THREAD

**Issue by ngthanhtin** [uzh-rpg/agile_flight#34]
Hi, could you please let me know where is the goal coordinates of each environment specified?
Thanks

**Comment by yun-long** [comment]
hi @ngthanhtin 

It is in the README.

 The goal is to proceed as fast as possible 60m in positive x-direction without colliding into obstacles and exiting a pre-defined bounding box. The parameters of the goal location and the bounding box can be found [here](https://github.com/uzh-rpg/agile_flight/blob/main/envtest/ros/evaluation_config.yaml).
