### ISSUE TITLE
reset env?

### ISSUE THREAD

**Issue by ngthanhtin** [uzh-rpg/agile_flight#35]
Hi I initialized the env as following:
```
      self.num_envs = self.env_sim_config["simulation"]["num_envs"]
      # load the Unity standardalone, make sure you have downloaded it.
      os.system(os.environ["FLIGHTMARE_PATH"] + "/flightrender/RPG_Flightmare.x86_64 &")
      self.env = VisionEnv_v1(dump(self.env_sim_config, Dumper=RoundTripDumper), False)
      self.env = wrapper.FlightEnvVec(self.env)
      self.env.reset(random=True)
```
For example, the num_envs is 4 meaning that I have 4 envs. So if when an env is done (done=True), how can I reset just this env.

Thanks.

**Comment by yun-long** [comment]
hi, the reset is done inside the vision_vec_env.cpp file. 

(here)[https://github.com/uzh-rpg/flightmare/blob/dev/version_22/flightlib/src/envs/vision_env/vision_vec_env.cpp#L124-L127]
