### ISSUE TITLE
What is the obstacle in Dodge drone challenge?

### ISSUE THREAD

**Issue by HarukiKozukapenguin** [uzh-rpg/agile_flight#44]
Checking the code in [`vision_env.cpp`](https://github.com/uzh-rpg/flightmare/blob/092ff357139b2e98fc92bcdee50f38f85b55246d/flightlib/src/envs/vision_env/vision_env.cpp),  `is_collision_` assumed to be a sphere. Does the Selections and Finals also treat this sphere as an obstacle? Or, Selections and Finals recognize trees and cars as obstacles?

**Comment by yun-long** [comment]
hi, we only consider sphere obstacles.
