### ISSUE TITLE
goal_vel ?

### ISSUE THREAD

**Issue by HarukiKozukapenguin** [uzh-rpg/agile_flight#45]
[ReadMe](https://github.com/uzh-rpg/agile_flight/blob/main/README.md#testing-todo) says "The goal is to proceed as fast as possible 60m in positive x-direction without colliding into obstacles and exiting a pre-defined bounding box". Then, what the [`goal_vel`](https://github.com/uzh-rpg/agile_flight/blob/b3710d2926e28d32368d176ee657072d5ec42a35/envtest/ros/rl_policy/PPO_1/config.yaml#L4) stands for? Should drone be such velocity when we reach the goal? Or there are no restriction for velosity?

**Comment by yun-long** [comment]
it is a hyperparameter that you can change

you can use adaptive goal velocity depending on how the distance between the current quadrotor and the goal position/

or, you don't need a goal velocity but minimize the distance between the current quadrotor and the goal positon.

**Comment by HarukiKozukapenguin** [comment]
Does _adaptive goal velocity_ mean "desired velocity for quadrotor"?
I think so because quadrotor [get penalty depending on gap between velocity of quadrotor and `goal_vel`](https://github.com/uzh-rpg/flightmare/blob/ee30f203df42596668ee4c386ce1e45aedeedb8c/flightlib/src/envs/vision_env/vision_env.cpp#L313-L314).
