### ISSUE TITLE
Goal check in RL

### ISSUE THREAD

**Issue by HarukiKozukapenguin** [uzh-rpg/agile_flight#48]
Thank you for interesting challenge!

I tried to learn quadrotor to move well.
I read code of [`vision_env.cpp`](https://github.com/uzh-rpg/flightmare/blob/092ff357139b2e98fc92bcdee50f38f85b55246d/flightlib/src/envs/vision_env/vision_env.cpp) and [`config.yaml`](https://github.com/uzh-rpg/flightmare/blob/092ff357139b2e98fc92bcdee50f38f85b55246d/flightpy/configs/vision/config.yaml) but there are no information of goal position (+x 60), so where is this information? or should I input this information when I want to use this information?

**Comment by yun-long** [comment]
the vision_env.cpp is just an example. you should change the code. 
for example, you have to define the goal position or goal velocity.
you should define terminal conditions. For example, when reaching the goal position, the episode is terminated.

**Comment by HarukiKozukapenguin** [comment]
OK. I will manage by myself.
