### ISSUE TITLE
ModuleNotFoundError: No module named 'rpg_baselines.torch'

### ISSUE THREAD

**Issue by LuanBaviloni** [uzh-rpg/agile_flight#5]
![image](https://user-images.githubusercontent.com/34331324/158933844-864f7b90-8600-46c8-924c-3775a5812928.png)

**Comment by rshube** [comment]
I ran into this issue as well- a quick fix for me was to change line 19 in `flightmare/flightpy/flightrl/setup.py` from 
`packages=['rpg_baselines'],`
to 
`packages=find_packages(),`

Hope this helps!

**Comment by yun-long** [comment]
alternatively, you can append the rpg_baselines path to your python path

```
export PYTHONPATH="${PYTHONPATH}:/path/to/flightpy/flightrl"
```

**Comment by LuanBaviloni** [comment]
Solved! Thank you guys!
