### ISSUE TITLE
Explicit obstacle information or images (different rank will apply).

### ISSUE THREAD

**Issue by nmharmon8** [uzh-rpg/agile_flight#55]
What is the meaning of "For evaluation, we will consider policies with access to either explicit obstacle information or images (different rank will apply)"

Can you still win if you use the explicit obstacle information?

**Comment by yun-long** [comment]
yes, you can will the state-based (using explicit obstacle information)  challenge. 

but for winning the first prize of 1000 CHF, it has to be vision-based.

**Comment by nmharmon8** [comment]
Thanks.
