### ISSUE TITLE
Flightmare Client IP

### ISSUE THREAD

**Issue by anahrendra** [uzh-rpg/agile_flight#6]
I am not sure with the IP for Flightmare, since I am still unable to connect to the simulator. Could you give any information about it? 

Thanks!

**Comment by yun-long** [comment]
Hi

Can you be more specific about "unable to connect to the simulator". is there any errors? is the Unity standalone running?

**Comment by anahrendra** [comment]
Hi!

Thanks for your reply. It seems my system settings were a bit messed up. 
I tried installing on a fresh Ubuntu environment, and it now works great! Thanks!
