### ISSUE TITLE
Domain randomization

### ISSUE THREAD

**Issue by HarukiKozukapenguin** [uzh-rpg/agile_flight#62]
Thank you for interesting challenge!

As you can see here, from the Simulation to the Real World, Domain Randomization is helpful. https://arxiv.org/abs/1703.06907

So, I would like to ask the parameters of quadrotor dynamics in Dodge drone challenge(https://github.com/uzh-rpg/flightmare/blob/092ff357139b2e98fc92bcdee50f38f85b55246d/flightpy/configs/vision/config.yaml#L45-L60). Do these parameters will change in the Selections and Finals? Or, do these parameters do not change?

**Comment by yun-long** [comment]
the dynamic parameters will stay the same during the evaluation. 
The only difference is that during training (if you are using Reinforcement learning), you are using a perfect simulation (no delay, no noise). 

During the evaluation, we will be using a ROS script. The ROS message publication and subscriber will have some delay, which is negligible normally. But, the performance might vary during evaluation. 

But, to answer your question. the dynamic parameters will not be changed. Not sure if Domain randomization will be a good idea in this case.

**Comment by HarukiKozukapenguin** [comment]
OK, I will check these delay, Thank you for your valuable information!
