### ISSUE TITLE
Error - roslaunch - RLException  Unable to launch [flight_render-5]

### ISSUE THREAD

**Issue by Andres1508** [uzh-rpg/agile_flight#7]
![error3](https://user-images.githubusercontent.com/10423825/159056071-f2bf0b96-6f45-4bb9-9b35-5cb9d511b674.jpg)

**Comment by yun-long** [comment]
Hi, can be more specific about which command did you use for launching?

Make sure that in this folder, these two files exist 

```
CMakeLists.txt 
package.xml
```

under the flighmare/flightrender

as well as the unity standalone, namely the RPG_Flightmare

**Comment by yun-long** [comment]
@Andres1508 

did you solve the issue? if you have more questions, feel free to post them here or open a new issue. Otherwise, I assume you have solved the problem and will close this issue.
