### ISSUE TITLE
Feedthrough command timing out

### ISSUE THREAD

**Issue by adrianjselva** [uzh-rpg/agile_flight#74]
I am attempting to publish the commands directly through the `/kingfisher/dodgeros_pilot/feedthrough_command` topic, but I am getting this error:

`[Pipeline]     Feedthrough command timed out: 0.060!`

I have tried modifying the feedthrough_timeout parameter in `dodgedrone_simulation/dodgeros/parameters/simple_sim_pilot.yaml` to different values, but the error persists. Is there anywhere else to adjust this timeout or a way to avoid getting a timeout in the first place?

**Comment by heyyeh12** [comment]
I think you need to publish on the `/kingfisher/dodgeros_pilot/feedthrough_command` faster than 20Hz (1/0.05s) to avoid this error, which appears to be hard-coded [here](https://github.com/uzh-rpg/dodgedrone_simulation/blob/9bb4456fa90930381336f4625345eb40ea911342/dodgelib/include/dodgelib/base/pipeline.hpp#L89)
